/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Legality.
 */
class Legality {
  /**
   * Create a Legality.
   * @property {string} [standard] Possible values include: 'legal',
   * 'not_legal', 'restricted', 'banned'
   * @property {string} [future] Possible values include: 'legal', 'not_legal',
   * 'restricted', 'banned'
   * @property {string} [frontier] Possible values include: 'legal',
   * 'not_legal', 'restricted', 'banned'
   * @property {string} [modern] Possible values include: 'legal', 'not_legal',
   * 'restricted', 'banned'
   * @property {string} [legacy] Possible values include: 'legal', 'not_legal',
   * 'restricted', 'banned'
   * @property {string} [pauper] Possible values include: 'legal', 'not_legal',
   * 'restricted', 'banned'
   * @property {string} [vintage] Possible values include: 'legal',
   * 'not_legal', 'restricted', 'banned'
   * @property {string} [penny] Possible values include: 'legal', 'not_legal',
   * 'restricted', 'banned'
   * @property {string} [commander] Possible values include: 'legal',
   * 'not_legal', 'restricted', 'banned'
   * @property {string} [onevOne] Possible values include: 'legal',
   * 'not_legal', 'restricted', 'banned'
   * @property {string} [duel] Possible values include: 'legal', 'not_legal',
   * 'restricted', 'banned'
   * @property {string} [brawl] Possible values include: 'legal', 'not_legal',
   * 'restricted', 'banned'
   */
  constructor() {
  }

  /**
   * Defines the metadata of Legality
   *
   * @returns {object} metadata of Legality
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'legality',
      type: {
        name: 'Composite',
        className: 'Legality',
        modelProperties: {
          standard: {
            required: false,
            serializedName: 'standard',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          future: {
            required: false,
            serializedName: 'future',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          frontier: {
            required: false,
            serializedName: 'frontier',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          modern: {
            required: false,
            serializedName: 'modern',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          legacy: {
            required: false,
            serializedName: 'legacy',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          pauper: {
            required: false,
            serializedName: 'pauper',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          vintage: {
            required: false,
            serializedName: 'vintage',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          penny: {
            required: false,
            serializedName: 'penny',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          commander: {
            required: false,
            serializedName: 'commander',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          onevOne: {
            required: false,
            serializedName: '1v1',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          duel: {
            required: false,
            serializedName: 'duel',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          },
          brawl: {
            required: false,
            serializedName: 'brawl',
            type: {
              name: 'Enum',
              allowedValues: [ 'legal', 'not_legal', 'restricted', 'banned' ]
            }
          }
        }
      }
    };
  }
}

module.exports = Legality;
