/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a ManaCost.
 */
class ManaCost {
  /**
   * Create a ManaCost.
   * @property {string} [cost]
   * @property {number} [cmc]
   * @property {string} [colors] Possible values include: 'W', 'U', 'B', 'R',
   * 'G'
   * @property {boolean} [colorless]
   * @property {boolean} [monocolored]
   * @property {boolean} [multicolored]
   */
  constructor() {
  }

  /**
   * Defines the metadata of ManaCost
   *
   * @returns {object} metadata of ManaCost
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'mana_cost',
      type: {
        name: 'Composite',
        className: 'ManaCost',
        modelProperties: {
          cost: {
            required: false,
            serializedName: 'cost',
            type: {
              name: 'String'
            }
          },
          cmc: {
            required: false,
            serializedName: 'cmc',
            type: {
              name: 'Number'
            }
          },
          colors: {
            required: false,
            serializedName: 'colors',
            type: {
              name: 'Enum',
              allowedValues: [ 'W', 'U', 'B', 'R', 'G' ]
            }
          },
          colorless: {
            required: false,
            serializedName: 'colorless',
            type: {
              name: 'Boolean'
            }
          },
          monocolored: {
            required: false,
            serializedName: 'monocolored',
            type: {
              name: 'Boolean'
            }
          },
          multicolored: {
            required: false,
            serializedName: 'multicolored',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = ManaCost;
